[package]
name = "encrypted-spaces-sdk-cache"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
encrypted-spaces-backend = { workspace = true }
encrypted-spaces-changelog-core = { workspace = true }
encrypted-spaces-storage-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
